name: api-consistem

services:
  api:
    image: api-consistem
    build: .
    restart: always
    ports:
      - '3311:3311'
    networks:
      - api-consistem-network
      
networks:
  api-consistem-network:
    driver: bridge